# Generated by Django 5.1.6 on 2025-06-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_expense_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('BILL', 'Bill'), ('FOOD', 'Food'), ('GROCERIES', 'Groceries'), ('GAS', 'Gas'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
