# Generated by Django 5.1.6 on 2025-04-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tip_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='gratuity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
