# Generated by Django 5.1.6 on 2025-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_paycheckcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheckcycle',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
