# Generated by Django 5.1.6 on 2025-04-16 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_paycheckcycle_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheckcycle',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly (Every 2 weeks)')], default='biweekly', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paycheckcycle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paycheck_cycle', to=settings.AUTH_USER_MODEL),
        ),
    ]
