# Generated by Django 5.1.6 on 2025-04-30 04:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_paycheckcycle_frequency_alter_paycheckcycle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='cash_made',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Cash Made ($)'),
        ),
        migrations.AddField(
            model_name='tip',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Hours Worked'),
        ),
    ]
