# Generated by Django 5.0.14 on 2026-03-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_savedurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='gratuity',
        ),
    ]
